routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('auth.login');
Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('auth.logout');

Route::post(
    '/login-process',
    [App\Http\Controllers\AuthController::class, 'processLoginForm']
)->name('auth.login-process');


Route::get(
    '/forgot-password',
    [App\Http\Controllers\AuthController::class, 'showForgotPasswordForm']
)->name('auth.forgot-password');

Route::post(
    '/forgot-password-process',
    [App\Http\Controllers\AuthController::class, 'processForgotPasswordForm']
)->name('auth.forgot-password-process');

Route::get(
    '/reset-password/{token}',
    [App\Http\Controllers\AuthController::class, 'showResetPasswordForm']
)->name('auth.reset-password');

Route::get('/reset-password-success', function () {
    return view('auth.password-reset-success');
}
)->name('auth.reset-password-success');

Route::post(
    '/reset-password-process/',
    [App\Http\Controllers\AuthController::class, 'processResetPasswordForm']
)->name('auth.reset-password-process');

Route::middleware(['auth'])->group(function () {
    Route::get(
        '/departments/find-user-departments/{userId}',
        array(DepartmentController::class, 'findUserDepartments')
    );
    Route::resource('departments', DepartmentController::class);

    Route::get('/users/find-career-journal/{userId}', array(UserController::class, 'findUserCareerJournal'));

    Route::get('/users/find/{userId}', array(UserController::class, 'findById'));

    Route::match(
        array(
            'GET',
            'POST'
        ),
        '/users/find',
        [UserController::class, 'findUsers']
    )->name('users.find');
    Route::post('/users/{id}', array(UserController::class, 'update'));
    Route::resource('users', UserController::class);
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Department extends Model
{
    use HasFactory;


    public function head()
    {
        return $this->belongsTo(User::class);
    }

    public function members()
    {
        return $this->belongsToMany(User::class, 'user_department')
            ->withPivot($this->getCreatedAtColumn());
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\JsonHttpResponseException;
use App\Http\Requests\DepartmentEditRequest;
use App\Personnel\Department\DepartmentEntity;
use App\Personnel\Department\DepartmentStore;
use App\Personnel\Department\DepartmentStoreException;
use App\Personnel\User\UserEntity;
use App\Personnel\User\UserStore;
use App\Personnel\User\UserStoreException;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;


class DepartmentController extends Controller
{
    public function index(Request $request, DepartmentStore $departmentStore): View
    {
        $filter = array();
        if ($request->get('find')) {
            $filter['find'] = $request->get('find');
        }

        try {
            $departments = $departmentStore->paginateDepartments($filter, array(), 8);
        } catch (DepartmentStoreException $e) {
            return view('departments.list', array('error' => $e->getMessage()));
        }

        return view(
            'departments.list',
            array(
                'departments' => $departments,
                'canStore' => $departmentStore->canStore()
            )
        );
    }

    public function show(int $id, DepartmentStore $departmentStore): View
    {
        try {
            $d = $departmentStore->findById($id);
        } catch (DepartmentStoreException $e) {
            return view('departments.show', array('error' => $e->getMessage()));
        }

        return view('departments.show', array('department' => $d));
    }

    public function edit(int $id, DepartmentStore $departmentStore): View
    {
        try {
            if (!$departmentStore->canUpdate($id)) {
                throw new UnauthorizedActionException('Недостаточно прав для редактирования отдела');
            }

            return view('departments.edit', array('department' => $departmentStore->findById($id)));

        } catch (DepartmentStoreException|UnauthorizedActionException $e) {
            return view('departments.edit', array('error' => $e->getMessage()));
        }
    }


    public function update(
        int $id,
        DepartmentEditRequest $request,
        DepartmentStore $departmentStore
    ): JsonResponse|Response {
        $department = $this->createFromRequest($request);
        $department->id = $id;

        try {
            $departmentStore->update($department);
        } catch (DepartmentStoreException $e) {
            throw new JsonHttpResponseException($e->getMessage());
        }

        return response()->noContent();
    }

    public function create(UserStore $userStore, DepartmentStore $departmentStore, Request $request): View
    {
        try {
            if (!$departmentStore->canStore()) {
                throw new UnauthorizedActionException('Недостаточно прав для создания отдела');
            }

            $department = new DepartmentEntity();
            $department->name = 'Новый отдел';
            $department->head = $userStore->findById($request->user()->id);

            return view('departments.edit', array('department' => $department));
        } catch (UserStoreException|UnauthorizedActionException $e) {
            return view('departments.edit', array('error' => $e->getMessage()));
        }
    }

    public function store(Request $request, DepartmentStore $departmentStore): JsonResponse
    {
        $department = $this->createFromRequest($request);

        try {
            return $this->jsonResponse(array(
                'id' => $departmentStore->store($department)
            ));

        } catch (DepartmentStoreException $e) {
            throw new JsonHttpResponseException($e->getMessage());
        }
    }

    public function destroy(int $id, DepartmentStore $departmentStore): RedirectResponse
    {
        try {
            $departmentStore->delete($id);
        } catch (DepartmentStoreException $e) {
            return back()->withErrors(array('deleteError' => $e->getMessage()));
        }

        return back();
    }

    public function findUserDepartments(DepartmentStore $departmentStore, int $userId): JsonResponse
    {
        try {
            $departments = $departmentStore->findUserDepartments($userId);

            return $this->jsonResponse(
                array_values($departments->toArray())
            );
        } catch (DepartmentStoreException $e) {
            throw new JsonHttpResponseException($e->getMessage());
        }
    }

    protected function createFromRequest(Request $request): DepartmentEntity
    {
        $department = new DepartmentEntity();

        $department->name = $request->get('name');
        $department->description = $request->get('description');
        $department->head->id = $request->get('headId');

        foreach ($request->get('membersIds') as $memberId) {
            $m = new UserEntity();
            $m->id = $memberId;

            $department->members[] = $m;
        }

        return $department;
    }
}

resources/views/departments/edit.blade.php
<?php

/**
 * @author MageAspect https://github.com/mageaspect
 */

use App\Personnel\Department\DepartmentEntity;


/** @var DepartmentEntity $department */
/** @var string $error */

$error = $error ?? null;
?>

@extends('layouts.app')

@section('content')
    @if($error)
        <page-header class="bg-oce" title="Редактирование отдела">
            <template v-slot:icon>
                <i class="fas fa-layer-group"></i>
            </template>
            <template v-slot:buttons>
                <a href="{{ route('departments.index') }}" class="btn btn-light mr-4">
                    <span>К списку</span>
                </a>
            </template>
        </page-header>
        <error class="m-6 p-6 bg-oceanic-light" message="{{ $error }}"></error>
    @else
        <department-edit
            find-users-url="{{ route('users.find') }}"
            :json-department='@json($department, JSON_UNESCAPED_UNICODE)'>
        </department-edit>

    @endif
@endsection

resources/views/departments/list.blade.php
<?php

/**
 * @author MageAspect https://github.com/mageaspect
 */


/** @var \App\Personnel\Department\DepartmentEntity[] $departments */
?>

@extends('layouts.app')

@section('content')
    <page-header title="Список отделов">
        <template v-slot:icon>
            <i class="text-gray-dark fas fa-layer-group"></i>
        </template>
        <template v-slot:buttons>
            @if($canStore)
                <a href="{{ route('departments.create') }}" class="btn btn-primary">
                    <i class="fas fa-plus"></i>
                    <span>Добавить</span>
                </a>
            @endIf
        </template>
        <template v-slot:search>
            <form class="group relative ml-6" method="get">
                <svg width="20" height="20" fill="currentColor"
                     class="absolute left-3 top-1/2 -mt-2.5 text-gray-400 pointer-events-none
                            group-focus-within:text-blue-500"
                     aria-hidden="true">
                    <path fill-rule="evenodd"
                          clip-rule="evenodd"
                          d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414
                             1.414l-4.816-4.816A6 6 0 012 8z"/>
                </svg>
                <input class="focus:ring-2 focus:ring-blue focus:outline-none w-64 text-sm leading-6 bg-oceanic
                              text-gray-900 placeholder-gray-400 rounded-sm py-2 pl-10 ring-1 ring-gray-200 shadow-sm"
                       type="text"
                       name="find"
                       placeholder="Найти отдел..."
                       value="{{ request()->find }}">
            </form>
        </template>
    </page-header>
    <div class="grid p-6 grid-cols-departments gap-7">
        @foreach($departments as $department)
            <div class="border-oceanic-light border flex flex-col justify-between hover-ui-shadow">
                <div class="p-4 pb-8">
                    <a href="{{ route('departments.show', ['department' => $department->id]) }}"
                       class="pb-2 border-b border-oceanic-light text-gray-light link-gray-light text-lg font-medium">
                        {{ $department->name }}
                    </a>
                    <div class="my-5">
                        <div class="flex">
                            <div class="w-13 h-13 shrink-0 rounded-50% overflow-hidden">
                                <div class="w-inherit h-inherit bg-no-repeat bg-center bg-cover"
                                     style="@avatar($department->head->avatarPublicPath)"></div>
                            </div>
                            <div class="ml-4 font-medium">
                                <a href="{{ $department->head->profileUrl }}" class="mb-1 link-gray-light text-base">
                                    {{ $department->head->getFormattedName() }}
                                </a>
                                <div class="text-gray text-xs">{{ $department->head->position }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="text-sm leading-6 text-gray-lighter">
                        {{ $department->description }}
                    </div>
                </div>
                @if ($department->canBeUpdated || $department->canBeDeleted)
                    <div class="bg-oceanic-light p-1 flex justify-between text-2xs text-gray-lightest ">
                        @if ($department->canBeUpdated)
                            <a href="{{ route('departments.edit', ['department' => $department->id]) }}"
                               class="p-2 uppercase font-medium hover:text-green transition">редактировать</a>
                        @endif
                        @if ($department->canBeDeleted)
                            <form action="{{ route('departments.destroy', ['department' => $department->id]) }}"
                                  method="post">
                                @method('delete')
                                @csrf
                                <button type="submit" class="p-2 uppercase font-medium hover:text-red transition">
                                    Удалить
                                </button>
                            </form>
                        @endif
                    </div>
                @endif
            </div>
        @endforeach
    </div>
    <div class="px-6">
        {!! $departments->links() !!}
    </div>
@endsection

resources/views/departments/show.blade.php
<?php

/**
 * @author MageAspect https://github.com/mageaspect
 */


/** @var \App\Personnel\Department\DepartmentEntity $department */

$error = $error ?? null;
?>

@extends('layouts.app')

@section('content')
    @if($error)
        <page-header class="bg-oce" title="Просмотр отдела">
            <template v-slot:icon>
                <i class="fas fa-layer-group"></i>
            </template>
            <template v-slot:buttons>
                <a href="{{ route('departments.index') }}" class="btn btn-light mr-4">
                    <span>К списку</span>
                </a>
            </template>
        </page-header>
        <error class="m-6 p-6 bg-oceanic-light" message="{{ $error }}"></error>
    @else
        <department-show edit-url="{{ route('departments.edit', ['department' => $department->id]) }}"
                         list-url="{{ route('departments.index') }}"
                         :json-department='@json($department, JSON_UNESCAPED_UNICODE)'
        >
        </department-show>
    @endif
@endsection