routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('auth.login');
Route::get('/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('auth.logout');

Route::post(
    '/login-process',
    [App\Http\Controllers\AuthController::class, 'processLoginForm']
)->name('auth.login-process');


Route::get(
    '/forgot-password',
    [App\Http\Controllers\AuthController::class, 'showForgotPasswordForm']
)->name('auth.forgot-password');

Route::post(
    '/forgot-password-process',
    [App\Http\Controllers\AuthController::class, 'processForgotPasswordForm']
)->name('auth.forgot-password-process');

Route::get(
    '/reset-password/{token}',
    [App\Http\Controllers\AuthController::class, 'showResetPasswordForm']
)->name('auth.reset-password');

Route::get('/reset-password-success', function () {
    return view('auth.password-reset-success');
}
)->name('auth.reset-password-success');

Route::post(
    '/reset-password-process/',
    [App\Http\Controllers\AuthController::class, 'processResetPasswordForm']
)->name('auth.reset-password-process');

Route::middleware(['auth'])->group(function () {
    Route::get(
        '/departments/find-user-departments/{userId}',
        array(DepartmentController::class, 'findUserDepartments')
    );
    Route::resource('departments', DepartmentController::class);

    Route::get('/users/find-career-journal/{userId}', array(UserController::class, 'findUserCareerJournal'));

    Route::get('/users/find/{userId}', array(UserController::class, 'findById'));

    Route::match(
        array(
            'GET',
            'POST'
        ),
        '/users/find',
        [UserController::class, 'findUsers']
    )->name('users.find');
    Route::post('/users/{id}', array(UserController::class, 'update'));
    Route::resource('users', UserController::class);
});

app/View/Components/AppSidebar.php
<?php

namespace App\View\Components;

use App\Personnel\User\UserStore;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\Component;
use Illuminate\Contracts\View\View;


class AppSidebar extends Component
{
    private UserStore $userStore;

    public function __construct(UserStore $userStore)
    {
        $this->userStore = $userStore;
    }

    public function render(): View
    {
        return view(
            'components.sidebar',
            array('user' => $this->userStore->findById(Auth::user()->id))
        );
    }
}

resources/views/layouts/app.blade.php
<?php
/**
 * @author MageAspect https://github.com/mageaspect
 */
?>

    <!doctype html>
<html class="h-full" lang="{{str_replace('_', '-', app()->getLocale())}}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{env('APP_NAME')}}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap&subset=cyrillic"
          rel="stylesheet">
    <link rel="stylesheet" href="{{ mix('/css/app.css') }}">
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon" />
</head>
<body class="font-sans h-full">
<div  class="h-full">
    <div class="flex  h-full bg-oceanic-light">
        <x-app-sidebar></x-app-sidebar>
        <div id="app" class=" ml-7 h-full bg-oceanic grow py-5 ui-y-scroll">
            @yield('content')
        </div>
    </div>
</div>
<script src="https://kit.fontawesome.com/c2de66263d.js" crossorigin="anonymous"></script>
<script src="{{ mix('/js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/auth.blade.php
<?php
/**
 * @author MageAspect https://github.com/mageaspect
 */
?>

    <!doctype html>
<html lang="{{str_replace('_', '-', app()->getLocale())}}" class="text-html-base bg-oceanic-light h-full">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{env('APP_NAME')}}</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ mix('/css/app.css') }}">
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon" />
</head>
<body class="font-sans h-full">
<div class="h-full">
    <div class="flex flex-col h-full">
        <div class="flex justify-between px-5 py-4 bg-oceanic">
            <div class="py-2 font-medium tracking-wide text-xl text-gray-light">
                Отдел кадров
            </div>
            <x-auth-menu></x-auth-menu>
        </div>
        @yield('content')
    </div>
</div>
</body>
</html>